vich_uploader:
    db_driver: orm

    mappings:
        product_image:
           uri_prefix: /images/products
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

        category_image:
           uri_prefix: /images/products
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
