name: PHP Composer

on:
  push:

  pull_request:
    branches: [master]

jobs:
  build:
    name: Symfony
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: 7.3
          - php: 7.4
            symfony-version: ^4.4
          - php: 8.0

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@2.13.0
        with:
          php-version: '%{{ matrix.php }}'
          coverage: none

      - name: Update Symfony version
        if: matrix.symfony-version != ''
        run: composer require --no-update "symfony/symfony:${{matrix.symfony-version}}"

      - name: Install Composer dependencies
        run: composer update ${{matrix.composer-flags}}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # - name : PHP Unit test
      #   run: php .vendor/bin/phpunit
