name: PHP Composer

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@2.9.0
        with:
          tools: phpunit

      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Check Symfony Requirements
        run: vendor/bin/requirements-checker

      - name : PHP Unit test
        run: php .vendor/bin/phpunit
