name: Unit test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP with tools
      uses: shivammathur/setup-php@2.9.0
      with:
        tools: phpunit
    
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check PHP syntax errors
      uses: overtrue/phplint@2.3.0
      with:
        path: .
        options: --exclude=vendor
    
    - name : PHP Unit Test
      run: php bin/phpunit --testdox